### PR TITLE
net standard 2.1 update

### PR DESCRIPTION
**Pull request by xixaoly**
* lib target net45 to net standard 2.1 update
* tests target net 5 update
* RestSharp calls update

### CODE REVIEW

**Comment by michaldivis** [comment]
I'd like to support this PR. This is a much needed change.

**Comment by michaldivis** [comment]
This fixes my issue #15, please merge...

**Comment by michaldivis** [comment]
please merge this

**Comment by xpetrik** [comment]
It looks like @FSichinger died. Thank you @xixaoly for your work. We will use your PR and we will include source filles directly without nuget package.

**Comment by FSichinger** [comment]
Thanks for pull request and I apologize for late reply.

Next release will be available soon

**Comment by jiripolasek** [comment]
Hello,
is it necessary to upgrade all the way to .NET Standard 2.1 only? It limits the possible audience to .NET Core/.NET only as there is no .NET Framework that supports .NET Standard 2.1.

**Comment by xpetrik** [comment]
This is correct and necessary way to target both frameworks. @FSichinger will surely confirm this PR before he release nuget package

**Comment by jiripolasek** [comment]
The issue here is the version of .NET Standard used: targeting .NET Standard 2.0 (instead of 2.1) enables support for .NET Framework 4.6.1 - 4.8. Otherwise .NET Frameworks will be cut off.

**Pull request merged**
